package cn.com.taiji.entity;

public class Course {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.courseID
     *
     * @mbg.generated Wed Jan 09 11:47:48 CST 2019
     */
    private Integer courseid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.courseName
     *
     * @mbg.generated Wed Jan 09 11:47:48 CST 2019
     */
    private String coursename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.teacherID
     *
     * @mbg.generated Wed Jan 09 11:47:48 CST 2019
     */
    private Integer teacherid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.courseTIme
     *
     * @mbg.generated Wed Jan 09 11:47:48 CST 2019
     */
    private String coursetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.classRoom
     *
     * @mbg.generated Wed Jan 09 11:47:48 CST 2019
     */
    private String classroom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.courseWeek
     *
     * @mbg.generated Wed Jan 09 11:47:48 CST 2019
     */
    private Integer courseweek;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.courseType
     *
     * @mbg.generated Wed Jan 09 11:47:48 CST 2019
     */
    private String coursetype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.collegeID
     *
     * @mbg.generated Wed Jan 09 11:47:48 CST 2019
     */
    private Integer collegeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.score
     *
     * @mbg.generated Wed Jan 09 11:47:48 CST 2019
     */
    private Integer score;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.courseID
     *
     * @return the value of course.courseID
     *
     * @mbg.generated Wed Jan 09 11:47:48 CST 2019
     */
    public Integer getCourseid() {
        return courseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.courseID
     *
     * @param courseid the value for course.courseID
     *
     * @mbg.generated Wed Jan 09 11:47:48 CST 2019
     */
    public void setCourseid(Integer courseid) {
        this.courseid = courseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.courseName
     *
     * @return the value of course.courseName
     *
     * @mbg.generated Wed Jan 09 11:47:48 CST 2019
     */
    public String getCoursename() {
        return coursename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.courseName
     *
     * @param coursename the value for course.courseName
     *
     * @mbg.generated Wed Jan 09 11:47:48 CST 2019
     */
    public void setCoursename(String coursename) {
        this.coursename = coursename == null ? null : coursename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.teacherID
     *
     * @return the value of course.teacherID
     *
     * @mbg.generated Wed Jan 09 11:47:48 CST 2019
     */
    public Integer getTeacherid() {
        return teacherid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.teacherID
     *
     * @param teacherid the value for course.teacherID
     *
     * @mbg.generated Wed Jan 09 11:47:48 CST 2019
     */
    public void setTeacherid(Integer teacherid) {
        this.teacherid = teacherid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.courseTIme
     *
     * @return the value of course.courseTIme
     *
     * @mbg.generated Wed Jan 09 11:47:48 CST 2019
     */
    public String getCoursetime() {
        return coursetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.courseTIme
     *
     * @param coursetime the value for course.courseTIme
     *
     * @mbg.generated Wed Jan 09 11:47:48 CST 2019
     */
    public void setCoursetime(String coursetime) {
        this.coursetime = coursetime == null ? null : coursetime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.classRoom
     *
     * @return the value of course.classRoom
     *
     * @mbg.generated Wed Jan 09 11:47:48 CST 2019
     */
    public String getClassroom() {
        return classroom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.classRoom
     *
     * @param classroom the value for course.classRoom
     *
     * @mbg.generated Wed Jan 09 11:47:48 CST 2019
     */
    public void setClassroom(String classroom) {
        this.classroom = classroom == null ? null : classroom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.courseWeek
     *
     * @return the value of course.courseWeek
     *
     * @mbg.generated Wed Jan 09 11:47:48 CST 2019
     */
    public Integer getCourseweek() {
        return courseweek;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.courseWeek
     *
     * @param courseweek the value for course.courseWeek
     *
     * @mbg.generated Wed Jan 09 11:47:48 CST 2019
     */
    public void setCourseweek(Integer courseweek) {
        this.courseweek = courseweek;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.courseType
     *
     * @return the value of course.courseType
     *
     * @mbg.generated Wed Jan 09 11:47:48 CST 2019
     */
    public String getCoursetype() {
        return coursetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.courseType
     *
     * @param coursetype the value for course.courseType
     *
     * @mbg.generated Wed Jan 09 11:47:48 CST 2019
     */
    public void setCoursetype(String coursetype) {
        this.coursetype = coursetype == null ? null : coursetype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.collegeID
     *
     * @return the value of course.collegeID
     *
     * @mbg.generated Wed Jan 09 11:47:48 CST 2019
     */
    public Integer getCollegeid() {
        return collegeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.collegeID
     *
     * @param collegeid the value for course.collegeID
     *
     * @mbg.generated Wed Jan 09 11:47:48 CST 2019
     */
    public void setCollegeid(Integer collegeid) {
        this.collegeid = collegeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.score
     *
     * @return the value of course.score
     *
     * @mbg.generated Wed Jan 09 11:47:48 CST 2019
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.score
     *
     * @param score the value for course.score
     *
     * @mbg.generated Wed Jan 09 11:47:48 CST 2019
     */
    public void setScore(Integer score) {
        this.score = score;
    }
}