package cn.com.taiji.entity;

public class Role {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.roleID
     *
     * @mbg.generated Wed Jan 09 11:47:48 CST 2019
     */
    private Integer roleid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.roleName
     *
     * @mbg.generated Wed Jan 09 11:47:48 CST 2019
     */
    private String rolename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.permissions
     *
     * @mbg.generated Wed Jan 09 11:47:48 CST 2019
     */
    private String permissions;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.roleID
     *
     * @return the value of role.roleID
     *
     * @mbg.generated Wed Jan 09 11:47:48 CST 2019
     */
    public Integer getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.roleID
     *
     * @param roleid the value for role.roleID
     *
     * @mbg.generated Wed Jan 09 11:47:48 CST 2019
     */
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.roleName
     *
     * @return the value of role.roleName
     *
     * @mbg.generated Wed Jan 09 11:47:48 CST 2019
     */
    public String getRolename() {
        return rolename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.roleName
     *
     * @param rolename the value for role.roleName
     *
     * @mbg.generated Wed Jan 09 11:47:48 CST 2019
     */
    public void setRolename(String rolename) {
        this.rolename = rolename == null ? null : rolename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.permissions
     *
     * @return the value of role.permissions
     *
     * @mbg.generated Wed Jan 09 11:47:48 CST 2019
     */
    public String getPermissions() {
        return permissions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.permissions
     *
     * @param permissions the value for role.permissions
     *
     * @mbg.generated Wed Jan 09 11:47:48 CST 2019
     */
    public void setPermissions(String permissions) {
        this.permissions = permissions == null ? null : permissions.trim();
    }

    @Override
    public String toString() {
        return "Role{" +
                "roleid=" + roleid +
                ", rolename='" + rolename + '\'' +
                ", permissions='" + permissions + '\'' +
                '}';
    }
}