package cn.com.taiji.entity;

public class Selectedcourse extends SelectedcourseKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column selectedcourse.mark
     *
     * @mbg.generated Wed Jan 09 11:47:48 CST 2019
     */
    private Integer mark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column selectedcourse.mark
     *
     * @return the value of selectedcourse.mark
     *
     * @mbg.generated Wed Jan 09 11:47:48 CST 2019
     */
    public Integer getMark() {
        return mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column selectedcourse.mark
     *
     * @param mark the value for selectedcourse.mark
     *
     * @mbg.generated Wed Jan 09 11:47:48 CST 2019
     */
    public void setMark(Integer mark) {
        this.mark = mark;
    }
}