package cn.com.taiji.entity;

public class UserloginKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userlogin.userID
     *
     * @mbg.generated Wed Jan 09 11:47:48 CST 2019
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userlogin.role
     *
     * @mbg.generated Wed Jan 09 11:47:48 CST 2019
     */
    private Integer role;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userlogin.userID
     *
     * @return the value of userlogin.userID
     *
     * @mbg.generated Wed Jan 09 11:47:48 CST 2019
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userlogin.userID
     *
     * @param userid the value for userlogin.userID
     *
     * @mbg.generated Wed Jan 09 11:47:48 CST 2019
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userlogin.role
     *
     * @return the value of userlogin.role
     *
     * @mbg.generated Wed Jan 09 11:47:48 CST 2019
     */
    public Integer getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userlogin.role
     *
     * @param role the value for userlogin.role
     *
     * @mbg.generated Wed Jan 09 11:47:48 CST 2019
     */
    public void setRole(Integer role) {
        this.role = role;
    }
}