package cn.com.taiji.mapper;

import cn.com.taiji.entity.Selectedcourse;
import cn.com.taiji.entity.SelectedcourseExample;
import cn.com.taiji.entity.SelectedcourseKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SelectedcourseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table selectedcourse
     *
     * @mbg.generated Wed Jan 09 11:47:48 CST 2019
     */
    long countByExample(SelectedcourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table selectedcourse
     *
     * @mbg.generated Wed Jan 09 11:47:48 CST 2019
     */
    int deleteByExample(SelectedcourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table selectedcourse
     *
     * @mbg.generated Wed Jan 09 11:47:48 CST 2019
     */
    int deleteByPrimaryKey(SelectedcourseKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table selectedcourse
     *
     * @mbg.generated Wed Jan 09 11:47:48 CST 2019
     */
    int insert(Selectedcourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table selectedcourse
     *
     * @mbg.generated Wed Jan 09 11:47:48 CST 2019
     */
    int insertSelective(Selectedcourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table selectedcourse
     *
     * @mbg.generated Wed Jan 09 11:47:48 CST 2019
     */
    List<Selectedcourse> selectByExample(SelectedcourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table selectedcourse
     *
     * @mbg.generated Wed Jan 09 11:47:48 CST 2019
     */
    Selectedcourse selectByPrimaryKey(SelectedcourseKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table selectedcourse
     *
     * @mbg.generated Wed Jan 09 11:47:48 CST 2019
     */
    int updateByExampleSelective(@Param("record") Selectedcourse record, @Param("example") SelectedcourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table selectedcourse
     *
     * @mbg.generated Wed Jan 09 11:47:48 CST 2019
     */
    int updateByExample(@Param("record") Selectedcourse record, @Param("example") SelectedcourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table selectedcourse
     *
     * @mbg.generated Wed Jan 09 11:47:48 CST 2019
     */
    int updateByPrimaryKeySelective(Selectedcourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table selectedcourse
     *
     * @mbg.generated Wed Jan 09 11:47:48 CST 2019
     */
    int updateByPrimaryKey(Selectedcourse record);
}