package cn.com.taiji.mapper;

import cn.com.taiji.entity.Userlogin;
import cn.com.taiji.entity.UserloginExample;
import cn.com.taiji.entity.UserloginKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserloginMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userlogin
     *
     * @mbg.generated Wed Jan 09 11:47:48 CST 2019
     */
    long countByExample(UserloginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userlogin
     *
     * @mbg.generated Wed Jan 09 11:47:48 CST 2019
     */
    int deleteByExample(UserloginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userlogin
     *
     * @mbg.generated Wed Jan 09 11:47:48 CST 2019
     */
    int deleteByPrimaryKey(UserloginKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userlogin
     *
     * @mbg.generated Wed Jan 09 11:47:48 CST 2019
     */
    int insert(Userlogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userlogin
     *
     * @mbg.generated Wed Jan 09 11:47:48 CST 2019
     */
    int insertSelective(Userlogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userlogin
     *
     * @mbg.generated Wed Jan 09 11:47:48 CST 2019
     */
    List<Userlogin> selectByExample(UserloginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userlogin
     *
     * @mbg.generated Wed Jan 09 11:47:48 CST 2019
     */
    Userlogin selectByPrimaryKey(UserloginKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userlogin
     *
     * @mbg.generated Wed Jan 09 11:47:48 CST 2019
     */
    int updateByExampleSelective(@Param("record") Userlogin record, @Param("example") UserloginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userlogin
     *
     * @mbg.generated Wed Jan 09 11:47:48 CST 2019
     */
    int updateByExample(@Param("record") Userlogin record, @Param("example") UserloginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userlogin
     *
     * @mbg.generated Wed Jan 09 11:47:48 CST 2019
     */
    int updateByPrimaryKeySelective(Userlogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userlogin
     *
     * @mbg.generated Wed Jan 09 11:47:48 CST 2019
     */
    int updateByPrimaryKey(Userlogin record);


    //找到userid的最大值
    Integer maxUserid() throws Exception;
}